SportStore/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SportStore.Models
{
    public class Cart
    {
        private List<OrderLine> selections = new List<OrderLine>();
        public Cart AddItem(Product p, int quantity)
        {
            OrderLine line = selections.Where(l => l.ProductId == p.Id)
                                       .FirstOrDefault();

            if (line != null)
            {
                line.Quantity += quantity;
            }
            else
            {
                selections.Add(new OrderLine
                {
                    ProductId = p.Id,
                    Product = p,
                    Quantity = quantity
                });
            }
            return this;
        }

        public Cart RemoveItem(long productId)
        {
            selections.RemoveAll(l => l.ProductId == productId);
            return this;
        }

        public void Clear() => selections.Clear();
        public IEnumerable<OrderLine> Selections { get => selections; }

    }
}

SportStore/Controllers/CartController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using SportStore.Infrastructure;
using SportStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SportStore.Controllers
{
    [ViewComponent(Name = "Cart")]
    public class CartController : Controller
    {
        private IRepository productRepository;
        private IOrderRepository ordersRepository;
        public CartController(IRepository prepo, IOrderRepository orepo)
        {
            productRepository = prepo;
            ordersRepository = orepo;
        }
        public IActionResult Index(string returnUrl)
        {
            ViewBag.returnUrl = returnUrl;
            return View(GetCart());
        }
        [HttpPost]
        public IActionResult AddToCart(Product product, string returnUrl)
        {
            SaveCart(GetCart().AddItem(product, 1));
            return RedirectToAction(nameof(Index), new { returnUrl });
        }
        [HttpPost]
        public IActionResult RemoveFromCart(long productId, string returnUrl)
        {
            SaveCart(GetCart().RemoveItem(productId));
            return RedirectToAction(nameof(Index), new { returnUrl });
        }
        public IActionResult CreateOrder()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateOrder(Order order)
        {
            order.Lines = GetCart().Selections.Select(s => new OrderLine
            {
                ProductId = s.ProductId,
                Quantity = s.Quantity
            }).ToArray();
            ordersRepository.AddOrder(order);
            SaveCart(new Cart());
            return RedirectToAction(nameof(Completed));
        }
        public IActionResult Completed() => View();
        private Cart GetCart() =>
            HttpContext.Session.GetJson<Cart>("Cart") ?? new Cart();
        private void SaveCart(Cart cart) =>
            HttpContext.Session.SetJson("Cart", cart);

        public IViewComponentResult Invoke(ISession session)
        {
            return new ViewViewComponentResult()
            {
                ViewData = new ViewDataDictionary<Cart>(ViewData,
                    session.GetJson<Cart>("Cart"))
            };
        }

    }
}

SportStore/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SportStore.Models;
using SportStore.Models.Paging;

namespace SportStore.Controllers
{
    public class StoreController : Controller
    {
        private IRepository _productRepo;
        private ICategoryRepository _categoryRepo;

        public StoreController(IRepository repository, ICategoryRepository categoryRepository)
        {
            _productRepo = repository;
            _categoryRepo = categoryRepository;
        }

        public IActionResult Index([FromQuery(Name ="options")] QueryOptions productOptions, QueryOptions catOptions, long category)
        {
            ViewBag.Categories = _categoryRepo.GetCategories(catOptions);
            ViewBag.SelectedCategory = category;
            return View(_productRepo.GetProduct(productOptions, category));
        }
    }
}

SportStore/Views/Cart/Completed.cshtml
@{
    Layout = "~/Views/Store/_Layout.cshtml";
}
<div class="text-center m-4">
    <h2>Thanks!</h2>
    <p>Thanks for placing your order.</p>
    <p>We'll ship your goods as soon as possible.</p>
    <a asp-action="Index" asp-controller="Store"
       class="btn btn-primary">
        OK
    </a>
</div>

SportStore/Views/Cart/CreateOrder.cshtml
@model Order
@{
    Layout = "~/Views/Store/_Layout.cshtml";
}
<h2 class="m-3">Your Details</h2>
<form asp-action="CreateOrder" method="post" class="m-4">
    <div class="form-group">
        <label>Your Name:</label>
        <input asp-for="CustomerName" class="form-control" />
    </div>
    <div class="form-group">
        <label> Your Address</label>
        <input asp-for="Address" class="form-control" />
    </div>
    <div class="form-group">
        <label>Your State:</label>
        <input asp-for="State" class="form-control" />
    </div>
    <div class="form-group">
        <label>Your Zip Code:</label>
        <input asp-for="ZipCode" class="form-control" />
    </div>
    <div class="text-center m-2">
        <button type="submit" class="btn btn-primary">Place Order</button>
        <a asp-action="Index" class="btn btn-secondary">Cancel</a>
    </div>
</form>

SportStore/Views/Cart/Index.cshtml
@model Cart
@{
    Layout = "~/Views/Store/_Layout.cshtml";
}
<h2 class="m-3">Your Cart</h2>
<div class="container-fluid">
    <div class="row">
        <div class="col font-weight-bold">Quantity</div>
        <div class="col font-weight-bold">Product</div>
        <div class="col font-weight-bold text-right">Price</div>
        <div class="col font-weight-bold text-right">Subtotal</div>
        <div class="col"></div>
    </div>
    @if (Model.Selections.Count() == 0)
    {
        <div class="row mt-2"><div class="col-12"><h4>Cart is Empty</h4></div></div>
    }
    else
    {
        @foreach (OrderLine line in Model.Selections)
        {
            <div class="row mt-1">
                <div class="col">@line.Quantity</div>
                <div class="col">@line.Product.Name</div>
                <div class="col text-right">
                    $@line.Product.RetailPrice.ToString("f2")
                </div>
                <div class="col text-right">
                    $@((line.Product.RetailPrice
                               * line.Quantity).ToString("f2"))
                </div>
                <div class="col">
                    <form asp-action="RemoveFromCart">
                        <button type="submit" name="productId"
                                value="@line.ProductId"
                                class="btn btn-sm btn-outline-danger">
                            Remove
                        </button>
                    </form>
                </div>
            </div>
        }
    }
    <div class="row mt-2">
        <div class="col"></div>
        <div class="col"></div>
        <div class="col text-right font-weight-bold">Total:</div>
        <div class="col text-right font-weight-bold">
            $@(Model.Selections.Sum(l => l.Product.RetailPrice
                       * l.Quantity).ToString("f2"))
        </div>
        <div class="col"></div>
    </div>
</div>
<div class="text-center m-2">
    @if (ViewBag.returnUrl != null)
    {
        <a href="@ViewBag.returnUrl" class="btn btn-outline-primary">
            Continue Shopping
        </a>
    }
    <a asp-action="CreateOrder" class="btn btn-primary">
        Place Order
    </a>
</div>