SportStore/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using SportStore.Models;
using SportStore.Models.Paging;

namespace SportStore.Controllers
{
    public class CategoriesController : Controller
    {
        private ICategoryRepository repository;
        public CategoriesController(ICategoryRepository repo) => repository = repo;

        public IActionResult Index(QueryOptions options)
        {
            ViewBag.searches = new string[] { "Name", "Description" };
            ViewBag.sorts = new string[] { "Name", "Description" };

            return View(repository.GetCategories(options));
        }

        [HttpPost]
        public IActionResult AddCategory(Category category)
        {
            repository.AddCategory(category);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult EditCategory(long id)
        {
            ViewBag.EditId = id;
            return View("Index", repository.Categories);
        }

        [HttpPost]
        public IActionResult UpdateCategory(Category category)
        {
            repository.UpdateCategory(category);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult DeleteCategory(Category category)
        {
            repository.DeleteCategory(category);
            return RedirectToAction(nameof(Index));
        }
    }
}

SportStore/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SportStore.Models;

namespace SportStore.Controllers
{
    public class OrderController : Controller
    {
        private IRepository _repository;
        private ICategoryRepository _categoryRepository;
        private IOrderRepository _orderRepository;

        public OrderController(IRepository repository, ICategoryRepository categoryRepository, IOrderRepository orderRepository)
        {
            _repository = repository;
            _categoryRepository = categoryRepository;
            _orderRepository = orderRepository;
        }

        public IActionResult Index()
        {
            return View(_orderRepository.Orders);
        }

        public IActionResult CreateOrder()
        {
            Order order = new Order();
            List<OrderLine> orderLines = new List<OrderLine>();
            foreach (Product product in _repository.Products)
            {
                OrderLine orderLine = new OrderLine();
                orderLine.OrderId = order.Id;
                orderLine.ProductId = product.Id;
                orderLine.Quantity = 0;
                orderLine.Product = product;
                orderLines.Add(orderLine);
            }

            ViewBag.lines = orderLines;
            return View(order);
        }

        [HttpPost]
        public IActionResult CreateOrder(Order order)
        {
            _orderRepository.AddOrder(order);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult EditOrder(long key)
        {
            return View(_orderRepository.GetOrder(key));
        }

        [HttpPost]
        public IActionResult EditOrder(Order order)
        {
            _orderRepository.UpdateOrder(order);
            return RedirectToAction(nameof(Index));
        }
    }
}

SportStore/Controllers/SeedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SportStore.Models;

namespace SportStore.Controllers
{
    public class SeedController : Controller
    {
        private DataContext context;
        public SeedController(DataContext ctx) => context = ctx;
        public IActionResult Index()
        {
            ViewBag.Count = context.Products.Count();
            return View(context.Products.Include(p => p.Category).OrderBy(p => p.Id).Take(20));
        }

        [HttpPost]
        public IActionResult CreateSeedData(int count)
        {
            ClearData();
            if (count > 0)
            {
                context.Database.SetCommandTimeout(System.TimeSpan.FromMinutes(10));
                context.Database
                       .ExecuteSqlCommand("DROP PROCEDURE IF EXISTS CreateSeedData");
                context.Database.
                        ExecuteSqlCommand($@"
                         CREATE PROCEDURE CreateSeedData
                         @RowCount decimal
                         AS
                         BEGIN
                             SET NOCOUNT ON
                             DECLARE @i INT = 1;
                             DECLARE @catId BIGINT;
                             DECLARE @CatCount INT = @RowCount / 10;
                             DECLARE @pprice DECIMAL(5,2);
                             DECLARE @rprice DECIMAL(5,2);
                             BEGIN TRANSACTION
                                WHILE @i <= @CatCount
                                BEGIN
                                    INSERT INTO Categories (Name, Description)
                                    VALUES (CONCAT('Category-', @i), 'Test Data Category');
                                    SET @catId = SCOPE_IDENTITY();
                                    DECLARE @j INT = 1;
                                    WHILE @j <= 10
                                    BEGIN
                                        SET @pprice = RAND()*(500-5+1);
                                        SET @rprice = (RAND() * @pprice) + @pprice;
                                        INSERT INTO Products (Name, CategoryId, PurchasePrice, RetailPrice)
                                        VALUES (CONCAT('Product', @i, '-', @j), @catId, @pprice, @rprice)
                                        SET @j = @j + 1
                                    END
                                    SET @i = @i + 1
                                END
                                COMMIT
                             END");
                context.Database.BeginTransaction();
                context.Database.ExecuteSqlCommand($"EXEC CreateSeedData @RowCount = {count}");
                context.Database.CommitTransaction();
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult ClearData()
        {
            context.Database.SetCommandTimeout(System.TimeSpan.FromMinutes(10));
            context.Database.BeginTransaction();
            context.Database.ExecuteSqlCommand("DELETE FROM Orders");
            context.Database.ExecuteSqlCommand("DELETE FROM Categories");
            context.Database.ExecuteSqlCommand("DELETE FROM Products");
            context.Database.CommitTransaction();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult CreateProductionData()
        {
            ClearData();

            context.Categories.AddRange(
                new Category
                {
                    Name = "Watersports",
                    Description = "Make a splash",
                    Products = new Product[]
                    {
                        new Product
                        {
                            Name = "Kayak",
                            Description = "A boat for one person",
                            PurchasePrice = 200, RetailPrice = 275
                        },
                        new Product
                        {
                            Name = "Lifejacket",
                            Description = "Protective and fashionable",
                            PurchasePrice = 40,
                            RetailPrice = 48.95m
                        },
                    }
                },
                new Category
                {
                    Name = "Soccer",
                    Description = "The World's Favorite Game",
                    Products = new Product[]
                    {
                        new Product
                        {
                             Name = "Soccer Ball",
                             Description = "FIFA-approved size and weight",
                             PurchasePrice = 18,
                             RetailPrice = 19.50m
                        },
                        new Product
                        {
                            Name = "Corner Flags",
                            Description = "Give your playing field a professional touch",
                            PurchasePrice = 32.50m,
                            RetailPrice = 34.95m
                        },
                        new Product
                        {
                            Name = "Stadium",
                            Description = "Flat-packed 35,000-seat stadium",
                            PurchasePrice = 75000,
                            RetailPrice = 79500
                        }
                    }
                },
                new Category
                {
                    Name = "Chess",
                    Description = "The Thinky Game",
                    Products = new Product[]
                    {
                        new Product
                        {
                            Name = "Thinking Cap",
                            Description = "Improve brain efficiency by 75%",
                            PurchasePrice = 10,
                            RetailPrice = 16
                        },
                        new Product
                        {
                            Name = "Unsteady Chair",
                            Description = "Secretly give your opponent a disadvantage",
                            PurchasePrice = 28,
                            RetailPrice = 29.95m
                         },
                         new Product
                         {
                            Name = "Human Chess Board",
                            Description = "A fun game for the family",
                            PurchasePrice = 68.50m,
                            RetailPrice = 75
                         },
                         new Product
                         {
                            Name = "Bling-Bling King",
                            Description = "Gold-plated, diamond-studded King",
                            PurchasePrice = 800,
                            RetailPrice = 1200
                         }
                    }
                }
            );

            context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

SportStore/Views/Shared/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SportsStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>
    <div class="p-2">
        @RenderBody()
    </div>
</body>
</html>

SportStore/Views/Shared/PageOptions.cshtml
<div class="container-fluid mt-2">
    <div class="row m-1">
        <div class="col"></div>
        <div class="col-1">
            <label class="col-form-label">Search</label>
        </div>
        <div class="col-3">
            <select form="pageform" name="options.searchpropertyname"
                    class="form-control">
                @foreach (string s in ViewBag.searches as string[])
                {
                    <option value="@s"
                            selected="@(Model.Options.SearchPropertyName == s)">
                        @(s.IndexOf('.') == -1 ? s : s.Substring(0, s.IndexOf('.')))
                    </option>
                }
            </select>
        </div>
        <div class="col">
            <input form="pageform" class="form-control" name="options.searchterm"
                   value="@Model.Options.SearchTerm" />
        </div>
        <div class="col-1 text-right">
            <button form="pageform" class="btn btn-secondary" type="submit">
                Search
            </button>
        </div>
        <div class="col"></div>
    </div>
    <div class="row m-1">
        <div class="col"></div>
        <div class="col-1">
            <label class="col-form-label">Sort</label>
        </div>
        <div class="col-3">
            <select form="pageform" name="options.OrderPropertyName"
                    class="form-control">
                @foreach (string s in ViewBag.sorts as string[])
                {
                    <option value="@s"
                            selected="@(Model.Options.OrderPropertyName == s)">
                        @(s.IndexOf('.') == -1 ? s : s.Substring(0, s.IndexOf('.')))
                    </option>
                }
            </select>
        </div>
        <div class="col form-check form-check-inline">
            <input form="pageform" type="checkbox" name="Options.DescendingOrder"
                   id="Options.DescendingOrder"
                   class="form-check-input" value="true"
                   checked="@Model.Options.DescendingOrder" />
            <label class="form-check-label">Descending Order</label>
        </div>
        <div class="col-1 text-right">
            <button form="pageform" class="btn btn-secondary" type="submit">
                Sort
            </button>
        </div>
        <div class="col"></div>
    </div>
</div>

SportStore/Views/Shared/Pages.cshtml
<form id="pageform" method="get" class="form-inline d-inline-block">
    <button name="options.currentPage" value="@(Model.CurrentPage -1)"
            class="btn btn-outline-primary @(!Model.HasPreviousPage ? "disabled" : "")"
            type="submit">
        Previous
    </button>
    @for (int i = 1; i <= 3 && i <= Model.TotalPages; i++)
    {
        <button name="options.currentPage" value="@i" type="submit"
                class="btn btn-outline-primary @(Model.CurrentPage == i ? "active" : "")">
            @i
        </button>
    }
    @if (Model.CurrentPage > 3 && Model.TotalPages - Model.CurrentPage >= 3)
    {
        @:...
        <button class="btn btn-outline-primary active">@Model.CurrentPage</button>
    }
    @if (Model.TotalPages > 3)
    {
        @:...
        @for (int i = Math.Max(4, Model.TotalPages - 2);
       i <= Model.TotalPages; i++)
        {
            <button name="options.currentPage" value="@i" type="submit"
                    class="btn btn-outline-primary
     @(Model.CurrentPage == i ? "active" : "")">
                    @i
                </button>
            }
     }
    <button name="options.currentPage" value="@(Model.CurrentPage +1)" type="submit"
            class="btn btn-outline-primary @(!Model.HasNextPage? "disabled" : "")">
        Next
    </button>
    <select name="options.pageSize" class="form-control ml-1 mr-1">
        @foreach (int val in new int[] { 10, 25, 50, 100 })
        {
            <option value="@val" selected="@(Model.PageSize == val)">@val</option>
        }
    </select>
    <input type="hidden" name="options.currentPage" value="1" />
    <button type="submit" class="btn btn-secondary">Change Page Size</button>
</form>

SportStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SportsStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>
    <div class="container-fluid">
        <div class="row p-2">
            <div class="col-2">
                <a asp-controller="Home" asp-action="Index"
                   class="@GetClassForButton("Home")">
                    Products
                </a>
                <a asp-controller="Categories" asp-action="Index"
                   class="@GetClassForButton("Categories")">
                    Categories
                </a>
                <a asp-controller="Order" asp-action="Index"
                   class="@GetClassForButton("Order")">
                    Order
                </a>
                <a asp-controller="Seed" asp-action="Index"
                   class="@GetClassForButton("Seed")">
                    Seed Data
                </a>
            </div>
            <div class="col">
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>

@functions {
    string GetClassForButton(string controller)
    {
        return "btn btn-block " + (ViewContext.RouteData.Values["controller"]
        as string == controller ? "btn-primary" : "btn-outline-primary");
    }
}